name: Add Artifact to release

on:
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  package:
    name: Package and add to release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java (temurin@11)
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Build project
        run: 'sbt universal:packageBin'

      - name: PWD
        run: pwd

      - name: LS
        run: ls -lah

      - name: Update Release with Files
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: false
          draft: false
          body: ${{ github.event.release.body }}
          name: ${{ github.event.release.name }}
          tag: ${{ github.event.release.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: '.\PoEArchnemesis/target/universal/poe.zip'
